/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAgentActivityRouteImport } from './routes/_authenticated/agent-activity'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBillingHistoryRouteImport } from './routes/_authenticated/billing-history'
import { Route as AuthenticatedClientBalancesRouteImport } from './routes/_authenticated/client-balances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeniedPaymentsRouteImport } from './routes/_authenticated/denied-payments'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedProspectsRouteImport } from './routes/_authenticated/prospects'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSendSmsRouteImport } from './routes/_authenticated/send-sms'
import { Route as AuthenticatedWonSalesRouteImport } from './routes/_authenticated/won-sales'
import { Route as AuthenticatedAdminAgentReportsRouteImport } from './routes/_authenticated/admin/agent-reports'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedAdminDataBackupRouteImport } from './routes/_authenticated/admin/data-backup'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminStageHistoryRouteImport } from './routes/_authenticated/admin/stage-history'
import { Route as AuthenticatedAdminStagesRouteImport } from './routes/_authenticated/admin/stages'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedSmsLogsRouteImport } from './routes/_authenticated/sms.logs'
import { Route as AuthenticatedSmsSendRouteImport } from './routes/_authenticated/sms.send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentActivityRoute =
  AuthenticatedAgentActivityRouteImport.update({
    id: '/agent-activity',
    path: '/agent-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingHistoryRoute =
  AuthenticatedBillingHistoryRouteImport.update({
    id: '/billing-history',
    path: '/billing-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientBalancesRoute =
  AuthenticatedClientBalancesRouteImport.update({
    id: '/client-balances',
    path: '/client-balances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeniedPaymentsRoute =
  AuthenticatedDeniedPaymentsRouteImport.update({
    id: '/denied-payments',
    path: '/denied-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspectsRoute = AuthenticatedProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendSmsRoute = AuthenticatedSendSmsRouteImport.update({
  id: '/send-sms',
  path: '/send-sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWonSalesRoute = AuthenticatedWonSalesRouteImport.update({
  id: '/won-sales',
  path: '/won-sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgentReportsRoute =
  AuthenticatedAdminAgentReportsRouteImport.update({
    id: '/agent-reports',
    path: '/agent-reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDataBackupRoute =
  AuthenticatedAdminDataBackupRouteImport.update({
    id: '/data-backup',
    path: '/data-backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStageHistoryRoute =
  AuthenticatedAdminStageHistoryRouteImport.update({
    id: '/stage-history',
    path: '/stage-history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStagesRoute =
  AuthenticatedAdminStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSmsLogsRoute = AuthenticatedSmsLogsRouteImport.update({
  id: '/sms/logs',
  path: '/sms/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmsSendRoute = AuthenticatedSmsSendRouteImport.update({
  id: '/sms/send',
  path: '/sms/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/billing-history': typeof AuthenticatedBillingHistoryRoute
  '/client-balances': typeof AuthenticatedClientBalancesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/denied-payments': typeof AuthenticatedDeniedPaymentsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send-sms': typeof AuthenticatedSendSmsRoute
  '/won-sales': typeof AuthenticatedWonSalesRoute
  '/admin/agent-reports': typeof AuthenticatedAdminAgentReportsRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/data-backup': typeof AuthenticatedAdminDataBackupRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/stage-history': typeof AuthenticatedAdminStageHistoryRoute
  '/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/sms/logs': typeof AuthenticatedSmsLogsRoute
  '/sms/send': typeof AuthenticatedSmsSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/billing-history': typeof AuthenticatedBillingHistoryRoute
  '/client-balances': typeof AuthenticatedClientBalancesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/denied-payments': typeof AuthenticatedDeniedPaymentsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send-sms': typeof AuthenticatedSendSmsRoute
  '/won-sales': typeof AuthenticatedWonSalesRoute
  '/admin/agent-reports': typeof AuthenticatedAdminAgentReportsRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/data-backup': typeof AuthenticatedAdminDataBackupRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/stage-history': typeof AuthenticatedAdminStageHistoryRoute
  '/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/sms/logs': typeof AuthenticatedSmsLogsRoute
  '/sms/send': typeof AuthenticatedSmsSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/agent-activity': typeof AuthenticatedAgentActivityRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/billing-history': typeof AuthenticatedBillingHistoryRoute
  '/_authenticated/client-balances': typeof AuthenticatedClientBalancesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/denied-payments': typeof AuthenticatedDeniedPaymentsRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/prospects': typeof AuthenticatedProspectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/send-sms': typeof AuthenticatedSendSmsRoute
  '/_authenticated/won-sales': typeof AuthenticatedWonSalesRoute
  '/_authenticated/admin/agent-reports': typeof AuthenticatedAdminAgentReportsRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/data-backup': typeof AuthenticatedAdminDataBackupRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/stage-history': typeof AuthenticatedAdminStageHistoryRoute
  '/_authenticated/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/sms/logs': typeof AuthenticatedSmsLogsRoute
  '/_authenticated/sms/send': typeof AuthenticatedSmsSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/agent-activity'
    | '/billing'
    | '/billing-history'
    | '/client-balances'
    | '/dashboard'
    | '/denied-payments'
    | '/follow-ups'
    | '/meetings'
    | '/opportunities'
    | '/prospects'
    | '/reports'
    | '/send-sms'
    | '/won-sales'
    | '/admin/agent-reports'
    | '/admin/backup'
    | '/admin/data-backup'
    | '/admin/services'
    | '/admin/stage-history'
    | '/admin/stages'
    | '/admin/users'
    | '/sms/logs'
    | '/sms/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/agent-activity'
    | '/billing'
    | '/billing-history'
    | '/client-balances'
    | '/dashboard'
    | '/denied-payments'
    | '/follow-ups'
    | '/meetings'
    | '/opportunities'
    | '/prospects'
    | '/reports'
    | '/send-sms'
    | '/won-sales'
    | '/admin/agent-reports'
    | '/admin/backup'
    | '/admin/data-backup'
    | '/admin/services'
    | '/admin/stage-history'
    | '/admin/stages'
    | '/admin/users'
    | '/sms/logs'
    | '/sms/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/agent-activity'
    | '/_authenticated/billing'
    | '/_authenticated/billing-history'
    | '/_authenticated/client-balances'
    | '/_authenticated/dashboard'
    | '/_authenticated/denied-payments'
    | '/_authenticated/follow-ups'
    | '/_authenticated/meetings'
    | '/_authenticated/opportunities'
    | '/_authenticated/prospects'
    | '/_authenticated/reports'
    | '/_authenticated/send-sms'
    | '/_authenticated/won-sales'
    | '/_authenticated/admin/agent-reports'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/data-backup'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/stage-history'
    | '/_authenticated/admin/stages'
    | '/_authenticated/admin/users'
    | '/_authenticated/sms/logs'
    | '/_authenticated/sms/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-activity': {
      id: '/_authenticated/agent-activity'
      path: '/agent-activity'
      fullPath: '/agent-activity'
      preLoaderRoute: typeof AuthenticatedAgentActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing-history': {
      id: '/_authenticated/billing-history'
      path: '/billing-history'
      fullPath: '/billing-history'
      preLoaderRoute: typeof AuthenticatedBillingHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-balances': {
      id: '/_authenticated/client-balances'
      path: '/client-balances'
      fullPath: '/client-balances'
      preLoaderRoute: typeof AuthenticatedClientBalancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/denied-payments': {
      id: '/_authenticated/denied-payments'
      path: '/denied-payments'
      fullPath: '/denied-payments'
      preLoaderRoute: typeof AuthenticatedDeniedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospects': {
      id: '/_authenticated/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedProspectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send-sms': {
      id: '/_authenticated/send-sms'
      path: '/send-sms'
      fullPath: '/send-sms'
      preLoaderRoute: typeof AuthenticatedSendSmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/won-sales': {
      id: '/_authenticated/won-sales'
      path: '/won-sales'
      fullPath: '/won-sales'
      preLoaderRoute: typeof AuthenticatedWonSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agent-reports': {
      id: '/_authenticated/admin/agent-reports'
      path: '/agent-reports'
      fullPath: '/admin/agent-reports'
      preLoaderRoute: typeof AuthenticatedAdminAgentReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/data-backup': {
      id: '/_authenticated/admin/data-backup'
      path: '/data-backup'
      fullPath: '/admin/data-backup'
      preLoaderRoute: typeof AuthenticatedAdminDataBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stage-history': {
      id: '/_authenticated/admin/stage-history'
      path: '/stage-history'
      fullPath: '/admin/stage-history'
      preLoaderRoute: typeof AuthenticatedAdminStageHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stages': {
      id: '/_authenticated/admin/stages'
      path: '/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AuthenticatedAdminStagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/sms/logs': {
      id: '/_authenticated/sms/logs'
      path: '/sms/logs'
      fullPath: '/sms/logs'
      preLoaderRoute: typeof AuthenticatedSmsLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms/send': {
      id: '/_authenticated/sms/send'
      path: '/sms/send'
      fullPath: '/sms/send'
      preLoaderRoute: typeof AuthenticatedSmsSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAgentReportsRoute: typeof AuthenticatedAdminAgentReportsRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminDataBackupRoute: typeof AuthenticatedAdminDataBackupRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminStageHistoryRoute: typeof AuthenticatedAdminStageHistoryRoute
  AuthenticatedAdminStagesRoute: typeof AuthenticatedAdminStagesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAgentReportsRoute: AuthenticatedAdminAgentReportsRoute,
    AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
    AuthenticatedAdminDataBackupRoute: AuthenticatedAdminDataBackupRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminStageHistoryRoute: AuthenticatedAdminStageHistoryRoute,
    AuthenticatedAdminStagesRoute: AuthenticatedAdminStagesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAgentActivityRoute: typeof AuthenticatedAgentActivityRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBillingHistoryRoute: typeof AuthenticatedBillingHistoryRoute
  AuthenticatedClientBalancesRoute: typeof AuthenticatedClientBalancesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeniedPaymentsRoute: typeof AuthenticatedDeniedPaymentsRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedProspectsRoute: typeof AuthenticatedProspectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSendSmsRoute: typeof AuthenticatedSendSmsRoute
  AuthenticatedWonSalesRoute: typeof AuthenticatedWonSalesRoute
  AuthenticatedSmsLogsRoute: typeof AuthenticatedSmsLogsRoute
  AuthenticatedSmsSendRoute: typeof AuthenticatedSmsSendRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAgentActivityRoute: AuthenticatedAgentActivityRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBillingHistoryRoute: AuthenticatedBillingHistoryRoute,
  AuthenticatedClientBalancesRoute: AuthenticatedClientBalancesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeniedPaymentsRoute: AuthenticatedDeniedPaymentsRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedProspectsRoute: AuthenticatedProspectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSendSmsRoute: AuthenticatedSendSmsRoute,
  AuthenticatedWonSalesRoute: AuthenticatedWonSalesRoute,
  AuthenticatedSmsLogsRoute: AuthenticatedSmsLogsRoute,
  AuthenticatedSmsSendRoute: AuthenticatedSmsSendRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
